spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/keycloak
    username: keycloak
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
